### ISSUE TITLE
Feedback for “Python Package”

### ISSUE THREAD

**Issue by Developerwant** [Noah-Haf/RankGunDocs#23]
I dont understand any of the rank gun this on this documntary. Please make it better and straight forward.

**Comment by Noah-Haf** [comment]
Yikes, how could we improve to make it better? Which page do you directly have problems with?

**Comment by Noah-Haf** [comment]
Feedback not issued

**Comment by Developerwant** [comment]
All I am trying to do is setup rankgun on my game so I can promote people by using ingame commands but all I see is API documentory and all kind of foolishness. I dont even see how to put the rank gun model in my game. I dont know how to pit it in my game and set it up. Also Rank gun Automation named tommy has not joined my game from so long. Ive been refreshing about a million times for him to join. Please fix all the issuesSent from my iPhoneOn 28 Oct 2023, at 7:32 PM, Noah Haf ***@***.***> wrote:﻿
Yikes, how could we improve to make it better? Which page do you directly have problems with?
