### ISSUE TITLE
I've been banned and don't know why, please help.

### ISSUE THREAD

**Issue by yesyesyes999** [Noah-Haf/RankGunDocs#38]
I've been banned from the Discord server and I don't know why. This happened a couple of weeks ago I think. The day before, I made a suggestion asking if you could make something (I forgot what it was, but it was nothing bad) and then the next day, I was banned. Please help because I am having trouble importing the Roblox ranking commands into Roblox and I need help.

**Comment by Noah-Haf** [comment]
Please contact me noah@rankgun.works we don't have any recollection of a user with your username being banned.
